export const TEST = 'TEST'
export const GRAPHQL_ACTION = 'GRAPHQL_ACTION'

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'

export const GET_MESSAGES = 'GET_MESSAGES'
export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
